
def build (bld) :
    if 'LIB_X11' in bld.env:
        for i in bld.path.ant_glob('*.c'):
            s = str(i)
            bld.program (source = s, target = s[:-2], use='X11', includes='/usr/include/sys', lib='m')

# vim: ft=python
