.TH XTOYS 1 "March 1999"
.SH XTOYS
xtoys \- Cellular automaton and wave equation simulators for X.
.SH SYNOPSIS
.B xising
.br
.B xpotts
.br
.B xautomalab
.br
.B xsand
.br
.B xfires
.br
.B xwaves
.br
.B schrodinger
.SH "DESCRIPTION"
.B xising:
implements a simulation of the two dimensional Ising model with both
local and cluster algorithms.
.PP
.B xpotts:
for the 
.I q
state Potts with a magnetic field.
.PP
.B xautomalab:
a totalistic cellular automaton simulator.
.PP
.B xsand:
implements the Bak, Tang, Wiesenfeld sandpile model, illustrating
self-organized criticality.
.PP
.B xfires:
a simple forest fire model of self-organized critiality.
.PP
.B xwaves:
simulates three different wave equations, representing light,
massive mesons, and water.
.PP
.B scrodinger:
evolves a wave function with the Schrodinger equation.  The
potential can be modified with the mouse.
.SH OPTIONS
No command line options are implemented.
.SH "SEE ALSO"
The programs are further documented in the files
.I readme.txt, xfires.txt, xpotts.txt, xwaves.txt,
.I xautomalab.txt, xising.txt, 
and 
.I xsand.txt,
included with the original source, available at the xtoys web page
.I http://thy.phy.bnl.gov/www/xtoys/xtoys.html.

.SH AUTHOR
The xtoys package and this manual page were written by Michael Creutz
<creutz@bnl.gov>.
