image: vbeffara/simulations

cmake:
  stage: build
  script:
    - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
    - conan create conan/yaml-cpp.py vbeffara/testing
    - conan create conan/libcmaes.py vbeffara/testing
    - mkdir -p build/cov
    - cd build
    - conan install .. --build missing
    - cmake .. -G Ninja -DCOV=1
    - ninja
  artifacts:
    paths:
      - build/

unittests:
  stage: test
  script:
    - Xvfb :4 &
    - export DISPLAY=:4
    - lcov -z -d build
    - ./build/tests/doctest
    - lcov -c -d build -d libvb -o build/cov/cov.info --no-external -q
    - codecov -t $CODECOV_TOKEN
    - coveralls-lcov -t $COVERALLS_TOKEN build/cov/cov.info
