image: ubuntu:latest

cmake:
  stage: build
  before-script:
    - apt-get update
    - apt-get install -y python-pip cmake gcc g++ ninja-build
    - apt-get install -y libcairo2-dev libfplll-dev libgmp-dev libmpfr-dev libgl1-mesa-dev
    - apt-get install -y libcln-dev libgsl-dev libeigen3-dev libpng++-dev mesa-common-dev
    - pip install codecov conan
    - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
    - conan remote add vb https://api.bintray.com/conan/vbeffara/misc
  script:
    - mkdir -p build/cov
    - cd build
    - conan install .. --build missing -s compiler.libcxx=libstdc++11
    - cmake .. -G Ninja -DCOV=1
    - ninja
  artifacts:
    paths:
      - build/

unittests:
  stage: test
  before-script:
    - apt-get update
    - apt-get install lcov ruby xvfb
    - gem install coveralls-lcov
    - pip install codecov conan
  script:
    - Xvfb :4 &
    - export DISPLAY=:4
    - lcov -z -d build
    - export LD_LIBRARY_PATH=./build/lib
    - ./build/tests/doctest
    - lcov -c -d build -d libvb -o build/cov/cov.info --no-external -q
    - codecov -t $CODECOV_TOKEN
    - coveralls-lcov -t $COVERALLS_TOKEN build/cov/cov.info
