image: ubuntu:latest

before_script:
  - apt-get update
  - apt-get install meson pkg-config cmake libfftw3-dev libdocopt-dev libboost-all-dev
  - apt-get install libcairo2-dev libeigen3-dev libfplll-dev libmsgsl-dev
  - apt-get install libspdlog-dev libtbb-dev libyaml-cpp-dev libfltk1.3-dev libmpc-dev
  - apt-get install clang

everything:
  stage: build
  script:
    - export CXX=clang++
    - meson setup builddir
    - ninja -C builddir
    - export LD_LIBRARY_PATH=./builddir/lib
    - xvfb-run -a builddir/catch2/catch2
