#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#define DOCTEST_CONFIG_SUPER_FAST_ASSERTS
#define UNIT_TESTS

#include <doctest.h>

#include <vb/Auto.h>
#include <vb/AutoWindow.h>
#include <vb/Automaton.h>
#include <vb/Bitmap.h>
#include <vb/CoarseImage.h>
#include <vb/Color.h>
#include <vb/Coloring.h>
#include <vb/Console.h>
#include <vb/Constellation.h>
#include <vb/Constellation0.h>
#include <vb/Constellation1.h>
#include <vb/Cube.h>
#include <vb/Elliptic.h>
#include <vb/Figure.h>
#include <vb/Hypermap.h>
#include <vb/Hypermap_lib.h>
#include <vb/Map.h>
#include <vb/Minimizer.h>
#include <vb/Path.h>
#include <vb/Picture.h>
#include <vb/Point.h>
#include <vb/Pov.h>
#include <vb/ProgressBar.h>
#include <vb/QuadTree.h>
#include <vb/Shape.h>
#include <vb/Sphere.h>
#include <vb/Spheroidal.h>
#include <vb/Toroidal.h>
#include <vb/data/Array.h>
#include <vb/data/TriMatrix.h>
#include <vb/math/LinearAlgebra.h>
#include <vb/math/NumberTheory.h>
#include <vb/math/Pairings.h>
#include <vb/math/Permutation.h>
#include <vb/math/Polynomial.h>
#include <vb/math/math.h>
#include <vb/util/CL_Parser.h>
#include <vb/util/Hub.h>
#include <vb/util/PRNG.h>
#include <vb/util/Stream.h>
#include <vb/util/coo.h>
#include <vb/util/cpx.h>
#include <vb/util/misc.h>
#include <vb/util/mp.h>
