
def build (bld) :
    bld.new_task_gen(features = 'cxx cshlib',
            source = bld.glob('*.cpp'),
            target = 'vb',
            includes = '.',
            export_incdirs = '.',
            uselib='FLTK png')
    bld.install_files ('${PREFIX}/include/vb', 'vb/*.h')

# vim: ft=python
