
def build (ctx) :
    ctx.shlib(source = ctx.path.ant_glob('*.cpp'),
              target = 'vb',
              includes = '.',
              export_includes = '.',
              use = 'FFTW3 FLTK CAIRO PNG')
    ctx.install_files ('${PREFIX}/include/vb', 'vb/*.h')

# vim: ft=python
