name: C/C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cxx: [g++, clang++]

    steps:
      - uses: actions/checkout@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install pkg-config cmake libfftw3-dev libdocopt-dev libboost-all-dev
          sudo apt-get install libcairo2-dev libeigen3-dev libfplll-dev libmsgsl-dev
          sudo apt-get install libspdlog-dev libtbb-dev libyaml-cpp-dev libfltk1.3-dev libmpc-dev
          sudo apt-get install clang
          uv python install
          uv sync

      - name: configure
        env:
          CXX: ${{ matrix.cxx }}
        run: |
          uv run conan install . --output-folder=build --build=missing
          (cd build ; cmake .. -G Ninja -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake" -DCMAKE_BUILD_TYPE=Release)

      - name: make
        run: ninja -C build

      - name: tests
        run: xvfb-run -a build/catch2/catch2
